### ISSUE TITLE
Problem when I try to build (Module build failed: TypeError: css.eachInside is not a function)

### ISSUE THREAD

**Issue by cpfarher** [mercs600/vue2-perfect-scrollbar#48]
It arise a problem when try to build webpack:

ERROR in ./~/css-loader?{"minimize":true}!./~/postcss-loader/lib?{"sourceMap":true}!./~/resolve-url-loader!./~/sass-loader/lib/loader.js?{"sourceMap":true}!./~/vue2-perfect-scrollbar/dist/vue2-perfect-scrollbar.min.css
    Module build failed: TypeError: css.eachInside is not a function
        at /node_modules/postcss-discard-comments/index.js:30:13
        at LazyResult.run /node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:270:20)
        at LazyResult.asyncTick (/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:185:32)
        at LazyResult.asyncTick (/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:197:22)
        at /postcss-loader/node_modules/postcss/lib/lazy-result.js:190:27
        at <anonymous>

**Comment by mercs600** [comment]
@cpfarher could you reproduce it and share repository ?
