### ISSUE TITLE
 error  in ./node_modules/vue2-perfect-scrollbar/dist/vue2-perfect-scrollbar.css

### ISSUE THREAD

**Issue by FENGLICHAO** [mercs600/vue2-perfect-scrollbar#5]
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'postcss-import'

**Comment by mercs600** [comment]
@FENGLICHAO we have 'postcss-import' in our dependencies. Do you have all required packages ?

**Comment by evsar3** [comment]
For some reason it didn't installed this dependency here too. I installed the package using this command:
`npm i -S vue2-perfect-scrollbar`

Then, to fix the issue I installed the missing dependency:
`npm i -SD postcss-import`

**Comment by chrisjenx** [comment]
@mercs600 not sure if it's an NPM bug, but same issue, `npm i vue2-perfect-scrollbar` doesn't seem to pull down that dependency :/

**Comment by breadadams** [comment]
Just ran into the same thing on build (during development it worked fine):

```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'postcss-import'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/breadadams/dev/projectname/node_modules/vue2-perfect-scrollbar/postcss.config.js:2:21)
    at Module._compile (module.js:652:30)
    at requireFromString (/Users/breadadams/dev/projectname/node_modules/require-from-string/index.js:28:4)
    at parseJsFile (/Users/breadadams/dev/projectname/node_modules/postcss-load-config/node_modules/cosmiconfig/dist/loadJs.js:15:15)
    at <anonymous>
    at runLoaders (/Users/breadadams/dev/projectname/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/breadadams/dev/projectname/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/breadadams/dev/projectname/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/breadadams/dev/projectname/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/breadadams/dev/projectname/node_modules/postcss-loader/src/index.js:208:9)
    at <anonymous>

 @ ./src/main.js 23:0-26
 @ ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js
```

The reason NPM isn't installing that dependency with the library is because it's marked as a devDependency, the solution would be to move it to `dependencies`.
